

DOCUMENT_SIZE: int = 4
NAME_LENGTH_SIZE: int = 1
BETS_LENGTH_SIZE: int = 2
BIRTH_DATE_SIZE: int = 4
BET_NUMBER_SIZE: int = 2

AGENCY_ID_SIZE: int = 4
PAYLOAD_LENGTH_SIZE: int = 4

ENDIAN = "big"


WINNER_LENGTH_SIZE: int = 4
